infrastructure/outputs.tf
Add separate DNS zones for storage blobs and queues.
---
=> feat: dtoss 3386 private endpoint updates - add separate storage zones

.azuredevops/pipelines/hub-infrastructure-dev.yaml
Switch the hub pipeline to run on the self-hosted Azure DevOps agents
---
=> feat: switch the hub infra pipeline to custom agent pool

.azuredevops/pipelines/hub-infrastructure-dev.yaml, infrastructure/baseline.tf, infrastructure/container_registry.tf, infrastructure/environments/development.tfvars.config, infrastructure/networking_hub.tf, infrastructure/providers.tf, infrastructure/variables.tf
Build the Azure Container Registry in the Hub
---
=> Feat: DTOSS-4839 move container registry to hub

infrastructure/container_registry.tf, infrastructure/environments/development.tfvars.config, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/private_dns.tf
=> feat: Add DNS Zone Resolver

infrastructure/config.tf, infrastructure/environments/development.tfvars.config, infrastructure/variables.tf, infrastructure/virtual-desktop.tf
Rather than adding a Bastion Host and standalone VMs, we decided to deploy Azure Virtual Desktop which would manage sessions automatically, directing connection requests to a session host with free capacity. Access to the VM is tunnelled over https via an AVD session broker once the user is authenticated with Entra ID, from this web page:
https://windows365.microsoft.com/ent#/devices
By using a Multi Session Windows 11 image, we can serve the compute requirements of multiple developers from a single VM, we can scale out easily by adding session hosts, and we can easily create separate host pools for separate teams if necessary.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID …
=> feat: DTOSS-3576 Azure Virtual Desktop

infrastructure/application_gateway.tf, infrastructure/config.tf, infrastructure/environments/development.tfvars.config, infrastructure/networking_hub.tf
Adds a bare Application Gateway to the hub.
Rules, backend pool, Health probe etc. to be added by each spoke infrastructure state.
Deploys the Azure Application Gateway which will allow API Management to be protected by a Web Application Firewall (WAF).
---
=> feat: DTOSS-4815 Application Gateway

.azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/config.tf, infrastructure/environments/development.tfvars.config, infrastructure/environments/production.tfvars.config, infrastructure/firewall.tf, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/variables.tf
Adding Firewall and associated Public IP components
---
=> feat: dtoss 3407 azure firewall deployment

infrastructure/baseline.tf, infrastructure/container_registry.tf, infrastructure/environments/development.tfvars.config, infrastructure/environments/production.tfvars.config, infrastructure/outputs.tf, infrastructure/private_dns.tf, infrastructure/variables.tf
Add private link service to Azure Monitor. Also separate project resources from hub resources via new "projects" map and resource groups.
---
=> feat: dtoss 5208 azure monitor private link

infrastructure/container_registry.tf
Fix ACR Private Endpoint Resource Group name
---
=> fix: ACR Private Endpoint Resource Group name

infrastructure/environments/development.tfvars.config
Container registry for Communication Manager
---
=> feat: DTOSS-4810 Communication Manager ACR

infrastructure/api-management.tf, infrastructure/environments/development.tfvars.config, infrastructure/variables.tf
This Pull Request deploys an Azure API Management (APIM) instance configured with the Developer SKU and capacity of 1 in the Development Hub. The APIM instance is set to internal mode to restrict access to within the Azure Virtual Network, and a public IP address is provisioned to manage controlled external access as needed.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …
=> Deploy and Configure APIM in Development Hub

infrastructure/api-management.tf, infrastructure/environments/production.tfvars.config
This Pull Request deploys an Azure API Management (APIM) instance configured with the Premium SKU and capacity of 3 in the Production Hub. The APIM instance is set to internal mode to restrict access to within the Azure Virtual Network, and a public IP address is provisioned to manage controlled external access as needed.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …
=> Addin API management to Production hub

.tool-versions, infrastructure/environments/development.tfvars
=> DTOSS-5412: Create the ACR for the service insights project

infrastructure/virtual_desktop.tf
Increases virtual desktops from 1 to 2.
---
=> Add an additional Virtual Desktop machine to the pool

.azuredevops/agent-pools/data.tf, .azuredevops/agent-pools/managed_devops_pool.tf, .azuredevops/agent-pools/variables.tf, .azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/data.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/providers.tf, infrastructure/variables.tf, infrastructure/virtual_desktop.tf
- Amend pipelines to use new YAML step templates, which now allow the Apply stage to optionally use PowerShell.
- Migrate variable groups to new naming pattern for Terraform backends.
- ADO agent-pools Terraform now uses a remote state lookup to determine target subnets.
- Improve parameterisation for Azure Virtual Desktop module, role assignments for AVD users and AVD admins.
Technical debt reduction.
[Successful deploy of Dev Hub](https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=5824&view=results) 
[Successful deploy of Dev ADO agents](https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=5828&view=results)
[Successful deploy of Prod Hub](https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=5831&view=results)
[Successful deploy of Prod ADO …
=> fix: DTOSS-5711 terraform pipeline changes for cert automation

.azuredevops/agent-pools/data.tf
Fix inconsistent variable name
---
=> fix: inconsistent variable name

.azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/baseline.tf, infrastructure/certificate.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/key_vault.tf, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/providers.tf, infrastructure/variables.tf
- Invoke new Terraform module for requesting SSL certificates, renewing them, and storing them in Key Vault.
- Add Key Vault to Hub for certificate storage, using private endpoint.
- Pipeline must now use build agent from Managed DevOps Pool to access this Key Vault.
Let's Encrypt offers free browser-trusted SSL certificates with a validity of 3 months, provided DNS domain ownership can be authenticated. By automating the requesting of these certificates using the certbot tool with an Azure DNS authoriser plugin, and persisting the certbot state in a Storage Account the entire process can be wrapped in Terraform.
When the pipeline runs, any existing certificate with less than 30 days until expiry will be automatically renewed, stored in the specified Key Vaults, and resources which use …
=> feat: DTOSS-5711 lets encrypt certificate automation

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml
Terraform apply stage modified to use PowerShell ready for Application Gateway Config module. This config will only be applied to the Hub, not per 'spoke' so it's not needed in the other projects.
---
=> fix: pipeline change ready for Application Gateway Config

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/environments/production.tfvars
Generate the SSL certificates for Production Hub, store them in Key Vault, output the Key Vault certificate IDs.
These certificates will be used for API Management and Application Gateway.
---
=> feat: DTOSS-3407 SSL Certificates for Prod Hub

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/baseline.tf, infrastructure/diagnostic_settings.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/key_vault.tf, infrastructure/locals.tf, infrastructure/log_analytics_workspace.tf, infrastructure/networking_hub.tf
Create Hub Log Analytics Workspace to send Hub based diagnostics data to.
---
=> feat: dtoss-5205 Create Prod Hub Log Analytics Workspace

infrastructure/dns_private.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/variables.tf
Add in postgres dns zone for the commgt project to be able to use the postgres database within the project VNET.
---
=> feat: Add in postgres dns zone

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/diagnostic_settings.tf, infrastructure/dns_private.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/event_hub.tf, infrastructure/key_vault.tf, infrastructure/outputs.tf, infrastructure/variables.tf
An event Hub is required to receive log data exported from the Audit Log Analytics Workspaces so that it can be forwarded to external SIEM tooling.
---
=> feat: DTOSS-5997 New Event Hub

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/outputs.tf, infrastructure/variables.tf
Updates to previous configuration of the Dev and Prod event hubs to match final requirements - no Event hub required in Dev Hub.
---
=> fix: dtoss-5996 Configure Dev and Prod Event Hubs

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/log_analytics_workspace.tf, infrastructure/outputs.tf, infrastructure/variables.tf
Amended Event Hub config after discussion with the client.
---
=> feat: dtoss 5997 amend eventhub config

.azuredevops/pipelines/hub-infrastructure-dev.yaml, infrastructure/azure_monitor_private_link_scope.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/outputs.tf
Architecture change to use a single Azure Monitor Private Link Service in the Hub.
---
=> fix: Log analytics private DNS

.azuredevops/agent-pools/variables.tf
Lower the Azure DevOps managed agent lifespan to 4 hrs to reduce the incidence of agents filling their storage.
---
=> fix: Lower Azure DevOps agent lifespan to 4 hours

.github/actions/create-lines-of-code-report/action.yaml, .github/actions/scan-dependencies/action.yaml
Update the GitHub Action workflow configurations to use version 4 (v4) to ensure compatibility with the latest features and fixes, as version 3 (v3) is now deprecated
---
=> feat: DTOS 6981 Updating github action from v3 and v4

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/api_management.tf, infrastructure/diagnostic_settings.tf, infrastructure/environments/production.tfvars
- Enabling diagnostics logging apim 
- Setting minimum api version to 2021-08-01.
- Changing the Off peak times for AVD scaling to 22:00
---
=> feat: dtos 7243 enabling diagnostics logging apim minimum api version

infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars
- Creation of Participant Manager ACR (Dev & Prod)
- Creation of Prod Service Insights
Successfully deployed to Dev Hub:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=15091&view=results
---
=> feat: DTOSS-7309 parman project setup

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/container_registry.tf, infrastructure/diagnostic_settings.tf
Creating diagnostic settings for ACR
---
=> feat: dtoss 7530 ds acr

infrastructure/diagnostic_settings.tf, infrastructure/environments/development.tfvars, infrastructure/event_grid_topic.tf, infrastructure/outputs.tf, infrastructure/rbac.tf, infrastructure/storage.tf, infrastructure/variables.tf
Update configuration to allow the event grid topics to be created within the Hub vnet rather than the project vnet. 
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=15747&view=results
---
=> feat: Add event grid hub

.azuredevops/pipelines/update-acr-public-ips.yaml
Recurring automation pipeline to update private DNS records in Live for the non-Live ACRs public IP addresses. Fix for a Continuous Deployment issue we have run into several times, which can be tricky to diagnose and resolve.
Container images need to be promoted from the non-live Azure Container Registry (ACR), to the live ACR. These are air-gapped on separate networks. However, the non-live ACR is publicly accessible (to allow the GitHub Actions CI process to connect).
Consequently we run the container image promotion pipeline from an ADO build agent on the live VNet, and reach out to the public IP of the non-live ACR. This allows us to communicate with ACRs on both sides, and to move container images between them. Since we do use private networking for ACRs on both sides, all DNS …
=> Feat: DTOSS-7887 Automate ACR private DNS updates

.azuredevops/pipelines/update-acr-public-ips.yaml
Instead of hourly all day weekdays, run the automation hourly from 08:00-19:00 on weekdays.
---
=> fix: DTOSS-7887 improve ACR ip update schedule

infrastructure/environments/development.tfvars, scripts/config/gitleaks.toml
This is for the dtos-tooling repository. Please note that this has already been deployed. 
---
=> Adding Dtos tooling ACR into hub

.azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, .azuredevops/pipelines/taint-avd-hosts-dev.yaml, .azuredevops/pipelines/taint-avd-hosts-prod.yaml, .azuredevops/pipelines/update-acr-public-ips.yaml
Automation pipeline for Terraform tainting the random component of AVD Session Host hostnames. This guarantees that their Entra ID domain identities will be new each time they are re-deployed. Rebuilding with the same hostnames breaks since we lack permission to delete the machine accounts in Entra ID.
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=16439&view=results
Resource tainting can be a bit involved, so this removes that complication and makes it easily repeatable.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive …
=> fix: DTOSS-7946 Taint AVD Session Hosts for re-deployment

.azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, .azuredevops/pipelines/taint-avd-hosts-dev.yaml, .azuredevops/pipelines/taint-avd-hosts-prod.yaml, .azuredevops/pipelines/update-acr-public-ips.yaml, infrastructure/environments/production.tfvars, infrastructure/variables.tf, infrastructure/virtual_desktop.tf
Within the Virtual Desktop module, virtual machine OS images can now be specified in three ways:
1. Source Image Reference (public images)
2. Source Image Gallery Reference (local private images)
3. Source Image ID (allows images in remote subscriptions, as long as managed identity has access)
This removes the need to copy the AVD image to a local compute gallery when updating from Dev to Prod. Azure makes that process very difficult, so this change greatly simplifies rolling out updates to the Azure Virtual Desktop image.
Deployed to Prod Hub in order to refresh the AVD hosts to an updated image:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=16630&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT …
=> Feat: Allow direct specification of AVD image_source_id parameter

infrastructure/dns_private.tf
Add Storage Account Table Service Private DNS Zone to hub so that we can create private endpoints for this service type in the projects.
---
=> feat: dtoss-7716 Add Storage Account Table Service Private DNS Zone

.azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, .azuredevops/pipelines/taint-avd-hosts-dev.yaml, .azuredevops/pipelines/taint-avd-hosts-prod.yaml, .azuredevops/pipelines/update-acr-public-ips.yaml, infrastructure/api_management.tf, infrastructure/application_gateway.tf, infrastructure/certificate.tf, infrastructure/data.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/providers.tf, infrastructure/variables.tf, scripts/config/gitleaks.toml
- Swapped out LetsEncrypt Certificates module for the new ACME Certificate module.
- To reduce confusion, certificate resource references now use a consistent naming key from creation though to consumption in other resources.
- Certificate resources (and downstream dependencies) are no longer flagged for replacement every single pipeline run, reducing noise from signal.
- Reduced other sources of `terraform plan` noise (AVD Host Pool load balancer type, GitHub Actions subnet metadata & tags, Application Gateway ssl_policy).
- Separated the API Management Custom Domains config from the main resource into a newer dedicated resource, which has overcome an inconsistent ordering bug that was also causing terraform to interpret changes needed on every plan.
Linked to:
- …
=> feat: DTOSS-9083 ACME certificate module

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml
Required for a change to Application Gatway SSL cert references, so they re-use the same consistent naming key which was used to mint them from ACME.
---
=> fix: Update templates repo ref

.azuredevops/pipelines/ado-agents-dev.yaml, .azuredevops/pipelines/ado-agents-prod.yaml, .azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, .azuredevops/pipelines/taint-avd-hosts-dev.yaml, .azuredevops/pipelines/taint-avd-hosts-prod.yaml, .azuredevops/pipelines/update-acr-public-ips.yaml, infrastructure/certificate.tf
Acme-certificate module improvements:
- Fix potential redirected DNS-01 challenge CNAME collisions.
- Add tags.
Linked to:
- https://github.com/NHSDigital/dtos-devops-templates/pull/171
- Successfully deployed to Hub Non-Live:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18586&view=results
- Successfully deployed to Hub Live:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18582&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will …
=> fix: ACME-certificate module improvements

infrastructure/firewall.tf
Azure Firewall Rule changes to permit egress traffic to Internet. Individual projects will need a new default route pointing at the Hub firewall to consolidate their egress traffic to originate from the Azure Firewall's public IP (to allow whitelisting for external services).
Successful deployment in Dev Hub:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=19253&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any …
=> feat: DTOSS-9463 Egress traffic via Azure firewall

.azuredevops/pipelines/hub-infrastructure-dev.yaml, .azuredevops/pipelines/hub-infrastructure-prod.yaml, infrastructure/container_registry.tf, infrastructure/data.tf, infrastructure/diagnostic_settings.tf, infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars, infrastructure/frontdoor.tf, infrastructure/key_vault.tf, infrastructure/networking_hub.tf, infrastructure/outputs.tf, infrastructure/variables.tf, scripts/config/gitleaks.toml
This change deploys the Azure Front Door Profile for the projects that need one.
Linked to:
- https://github.com/NHSDigital/dtos-devops-templates/pull/195
Testing:
- Successfully deployed to non-live Hub:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=20857&view=results
---
=> feat: DTOSS-8953 Azure Frontdoor deployment

.azuredevops/pipelines/hub-infrastructure-dev-multi-subscription.yaml, multi-subscription-infrastructure/activity_log_alert.tf, multi-subscription-infrastructure/environments/development.tfvars, multi-subscription-infrastructure/monitor_action_group.tf, multi-subscription-infrastructure/variables.tf
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=22314&view=logs&j=87cb0895-41d3-5206-c760-3bcd6869739a
As a DevOps Engineer, I want to set up Azure Service Health alerts for the UK region,
so that relevant stakeholders are promptly notified via email in the event of service issues, outages, or planned maintenance affecting regional resources on the following Azure Subscriptions:
SUBSCRIPTION NAME{} | SUBSCRIPTION ID -- | -- Digital Screening DToS - Core Services Dev{} | 67aab2fa-fcc7-49da-9dc6-cb90f0fa0628 Digital Screening DToS - Core Services Prod Hub{} | 950605a3-9919-4da7-8942-e46e388a3851 Digital Screening DToS - Audit NFT{} | a6831a46-5e7e-4039-9eab-fbf92545acbb Digital Screening DToS - Core Services Prod{} | 88d676e8-8caf-493e-80ef-0758f1278638 Digital Screening …
=> Feat: dtoss 9711 create azure service health alerts for uk region

infrastructure/environments/development.tfvars, infrastructure/environments/production.tfvars
Remove Communication Management Resources from Dev and Prod hubs.
---
=> fix: Remove Communication Management Resources
